# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Aug 21 20:40:26 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 687)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 821, 541))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.gdlyMain = QtWidgets.QGridLayout(self.horizontalLayoutWidget_4)
        self.gdlyMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gdlyMain.setContentsMargins(5, 5, 5, 5)
        self.gdlyMain.setObjectName("gdlyMain")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(240, 10, 551, 501))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.hzlyTbwResult = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hzlyTbwResult.setContentsMargins(5, 5, 5, 5)
        self.hzlyTbwResult.setObjectName("hzlyTbwResult")
        self.tbwResult = QtWidgets.QTableWidget(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbwResult.sizePolicy().hasHeightForWidth())
        self.tbwResult.setSizePolicy(sizePolicy)
        self.tbwResult.setAutoFillBackground(True)
        self.tbwResult.setLineWidth(2)
        self.tbwResult.setMidLineWidth(1)
        self.tbwResult.setWordWrap(False)
        self.tbwResult.setRowCount(0)
        self.tbwResult.setColumnCount(10)
        self.tbwResult.setObjectName("tbwResult")
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwResult.setHorizontalHeaderItem(8, item)
        self.hzlyTbwResult.addWidget(self.tbwResult)
        self.hzlyTbwResult.setStretch(0, 1)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 221, 501))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabTasks = QtWidgets.QTabWidget(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabTasks.sizePolicy().hasHeightForWidth())
        self.tabTasks.setSizePolicy(sizePolicy)
        self.tabTasks.setObjectName("tabTasks")
        self.tabTaskRuning = QtWidgets.QWidget()
        self.tabTaskRuning.setAutoFillBackground(False)
        self.tabTaskRuning.setObjectName("tabTaskRuning")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabTaskRuning)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 201, 461))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hzlyRunningTask = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hzlyRunningTask.setContentsMargins(5, 5, 5, 5)
        self.hzlyRunningTask.setObjectName("hzlyRunningTask")
        self.listRunningTasks = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listRunningTasks.setObjectName("listRunningTasks")
        self.hzlyRunningTask.addWidget(self.listRunningTasks)
        self.tabTasks.addTab(self.tabTaskRuning, "")
        self.tabTaskCompleted = QtWidgets.QWidget()
        self.tabTaskCompleted.setObjectName("tabTaskCompleted")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabTaskCompleted)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 201, 461))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hzlyCompletedTask = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hzlyCompletedTask.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hzlyCompletedTask.setContentsMargins(5, 5, 5, 5)
        self.hzlyCompletedTask.setObjectName("hzlyCompletedTask")
        self.listCompletedTasks = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.listCompletedTasks.setObjectName("listCompletedTasks")
        self.hzlyCompletedTask.addWidget(self.listCompletedTasks)
        self.tabTasks.addTab(self.tabTaskCompleted, "")
        self.horizontalLayout.addWidget(self.tabTasks)
        self.gdlyMain.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gdlyMain.setRowStretch(0, 1)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 580, 821, 75))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ltOutput = QtWidgets.QListWidget(self.horizontalLayoutWidget_6)
        self.ltOutput.setObjectName("ltOutput")
        self.horizontalLayout_2.addWidget(self.ltOutput)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuUser = QtWidgets.QMenu(self.menubar)
        self.menuUser.setObjectName("menuUser")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionTo_Excel = QtWidgets.QAction(MainWindow)
        self.actionTo_Excel.setObjectName("actionTo_Excel")
        self.actionNew_Task = QtWidgets.QAction(MainWindow)
        self.actionNew_Task.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionNew_Task.setObjectName("actionNew_Task")
        self.actionRegiste = QtWidgets.QAction(MainWindow)
        self.actionRegiste.setObjectName("actionRegiste")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionTo_File = QtWidgets.QAction(MainWindow)
        self.actionTo_File.setObjectName("actionTo_File")
        self.actionInsert = QtWidgets.QAction(MainWindow)
        self.actionInsert.setObjectName("actionInsert")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionStopAll = QtWidgets.QAction(MainWindow)
        self.actionStopAll.setObjectName("actionStopAll")
        self.menuExport.addAction(self.actionTo_Excel)
        self.menuExport.addAction(self.actionTo_File)
        self.menuFile.addAction(self.actionNew_Task)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.actionStop)
        self.menuFile.addAction(self.actionStopAll)
        self.menuUser.addAction(self.actionRegiste)
        self.menuUser.addAction(self.actionLogin)
        self.menuUser.addAction(self.actionLogout)
        self.menuEdit.addAction(self.actionInsert)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuUser.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabTasks.setCurrentIndex(0)
        self.tbwResult.cellChanged['int','int'].connect(MainWindow.itemChanged)
        self.tabTasks.tabBarClicked['int'].connect(MainWindow.tabTasksClicked)
        self.listCompletedTasks.itemClicked['QListWidgetItem*'].connect(MainWindow.completedTasksItemClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QT"))
        item = self.tbwResult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "公司"))
        item = self.tbwResult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "联系人"))
        item = self.tbwResult.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "联系电话"))
        item = self.tbwResult.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "手机"))
        item = self.tbwResult.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "传真"))
        item = self.tbwResult.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "邮编"))
        item = self.tbwResult.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "公司主页"))
        item = self.tbwResult.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "公司地址"))
        item = self.tbwResult.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "备注"))
        self.tabTaskRuning.setStatusTip(_translate("MainWindow", "Task is running"))
        self.tabTasks.setTabText(self.tabTasks.indexOf(self.tabTaskRuning), _translate("MainWindow", "未完成"))
        self.tabTasks.setTabText(self.tabTasks.indexOf(self.tabTaskCompleted), _translate("MainWindow", "已完成"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.menuUser.setTitle(_translate("MainWindow", "用户"))
        self.menuView.setTitle(_translate("MainWindow", "视图"))
        self.menuEdit.setTitle(_translate("MainWindow", "编辑"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionTo_Excel.setText(_translate("MainWindow", "To Excel"))
        self.actionNew_Task.setText(_translate("MainWindow", "New Task"))
        self.actionNew_Task.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionRegiste.setText(_translate("MainWindow", "Registe"))
        self.actionRegiste.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionTo_File.setText(_translate("MainWindow", "To File"))
        self.actionInsert.setText(_translate("MainWindow", "Insert"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStopAll.setText(_translate("MainWindow", "StopAll"))

