# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainframe.ui'
#
# Created: Wed Sep 10 17:46:45 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_new_task = QtWidgets.QWidget()
        self.tab_new_task.setObjectName("tab_new_task")
        self.tabWidget.addTab(self.tab_new_task, "")
        self.tab_running_tasks = QtWidgets.QWidget()
        self.tab_running_tasks.setObjectName("tab_running_tasks")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_running_tasks)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_tasks = QtWidgets.QGroupBox(self.tab_running_tasks)
        self.groupBox_tasks.setMaximumSize(QtCore.QSize(191, 16777215))
        self.groupBox_tasks.setObjectName("groupBox_tasks")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_tasks)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lw_processing_tasks = QtWidgets.QTableWidget(self.groupBox_tasks)
        self.lw_processing_tasks.setMinimumSize(QtCore.QSize(171, 0))
        self.lw_processing_tasks.setMaximumSize(QtCore.QSize(171, 16777215))
        self.lw_processing_tasks.setObjectName("lw_processing_tasks")
        self.lw_processing_tasks.setColumnCount(1)
        self.lw_processing_tasks.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.lw_processing_tasks.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lw_processing_tasks.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lw_processing_tasks.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.lw_processing_tasks.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.lw_processing_tasks.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.lw_processing_tasks)
        self.horizontalLayout_3.addWidget(self.groupBox_tasks)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_running_tasks)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tw_processing_task_details = QtWidgets.QTableWidget(self.groupBox_4)
        self.tw_processing_task_details.setObjectName("tw_processing_task_details")
        self.tw_processing_task_details.setColumnCount(0)
        self.tw_processing_task_details.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tw_processing_task_details)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_running_tasks, "")
        self.tab_completed_tasks = QtWidgets.QWidget()
        self.tab_completed_tasks.setObjectName("tab_completed_tasks")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_completed_tasks)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_completed_tasks)
        self.groupBox_3.setMaximumSize(QtCore.QSize(191, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lw_finished_tasks = QtWidgets.QListWidget(self.groupBox_3)
        self.lw_finished_tasks.setMaximumSize(QtCore.QSize(171, 16777215))
        self.lw_finished_tasks.setObjectName("lw_finished_tasks")
        item = QtWidgets.QListWidgetItem()
        self.lw_finished_tasks.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw_finished_tasks.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw_finished_tasks.addItem(item)
        self.verticalLayout_5.addWidget(self.lw_finished_tasks)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_completed_tasks)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tw_finished_task_details = QtWidgets.QTableWidget(self.groupBox_5)
        self.tw_finished_task_details.setObjectName("tw_finished_task_details")
        self.tw_finished_task_details.setColumnCount(0)
        self.tw_finished_task_details.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tw_finished_task_details)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_completed_tasks, "")
        self.tab_history = QtWidgets.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.tabWidget.addTab(self.tab_history, "")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.tabWidget.addTab(self.tab_search, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_new_task), _translate("MainWindow", "New Task"))
        self.groupBox_tasks.setTitle(_translate("MainWindow", "Tasks"))
        item = self.lw_processing_tasks.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建任务1"))
        item = self.lw_processing_tasks.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.lw_processing_tasks.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.lw_processing_tasks.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.lw_processing_tasks.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建列"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Task Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_running_tasks), _translate("MainWindow", "Running Tasks"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tasks"))
        __sortingEnabled = self.lw_finished_tasks.isSortingEnabled()
        self.lw_finished_tasks.setSortingEnabled(False)
        item = self.lw_finished_tasks.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.lw_finished_tasks.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.lw_finished_tasks.item(2)
        item.setText(_translate("MainWindow", "新建项目"))
        self.lw_finished_tasks.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(_translate("MainWindow", "Task Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_completed_tasks), _translate("MainWindow", "Completed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_history), _translate("MainWindow", "History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("MainWindow", "Search"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "open"))

