# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainframe.ui'
#
# Created: Thu Sep 11 21:25:09 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 555)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_new_task = QtWidgets.QWidget()
        self.tab_new_task.setObjectName("tab_new_task")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_new_task)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_new_task)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lb_current_site = QtWidgets.QPushButton(self.tab_new_task)
        self.lb_current_site.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lb_current_site.setFont(font)
        self.lb_current_site.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lb_current_site.setCheckable(False)
        self.lb_current_site.setFlat(True)
        self.lb_current_site.setObjectName("lb_current_site")
        self.horizontalLayout_4.addWidget(self.lb_current_site)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_task_name = QtWidgets.QLabel(self.tab_new_task)
        self.lb_task_name.setObjectName("lb_task_name")
        self.horizontalLayout_5.addWidget(self.lb_task_name)
        self.le_task_name = QtWidgets.QLineEdit(self.tab_new_task)
        self.le_task_name.setObjectName("le_task_name")
        self.horizontalLayout_5.addWidget(self.le_task_name)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb_search_conditions = QtWidgets.QLabel(self.tab_new_task)
        self.lb_search_conditions.setObjectName("lb_search_conditions")
        self.horizontalLayout_6.addWidget(self.lb_search_conditions)
        self.le_search_keywords = QtWidgets.QLineEdit(self.tab_new_task)
        self.le_search_keywords.setObjectName("le_search_keywords")
        self.horizontalLayout_6.addWidget(self.le_search_keywords)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pb_Ok = QtWidgets.QPushButton(self.tab_new_task)
        self.pb_Ok.setObjectName("pb_Ok")
        self.horizontalLayout_7.addWidget(self.pb_Ok)
        self.pb_Cancel = QtWidgets.QPushButton(self.tab_new_task)
        self.pb_Cancel.setObjectName("pb_Cancel")
        self.horizontalLayout_7.addWidget(self.pb_Cancel)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_new_task, "")
        self.tab_running_tasks = QtWidgets.QWidget()
        self.tab_running_tasks.setObjectName("tab_running_tasks")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_running_tasks)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_running_tasks)
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lw_processing_tasks = TaskRunningTable(self.groupBox_2)
        self.lw_processing_tasks.setMinimumSize(QtCore.QSize(100, 0))
        self.lw_processing_tasks.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lw_processing_tasks.setObjectName("lw_processing_tasks")
        self.lw_processing_tasks.setColumnCount(2)
        self.lw_processing_tasks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lw_processing_tasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lw_processing_tasks.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.lw_processing_tasks)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_running_tasks)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tw_processing_task_details = QtWidgets.QTableWidget(self.groupBox_4)
        self.tw_processing_task_details.setObjectName("tw_processing_task_details")
        self.tw_processing_task_details.setColumnCount(0)
        self.tw_processing_task_details.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tw_processing_task_details)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_running_tasks, "")
        self.tab_completed_tasks = QtWidgets.QWidget()
        self.tab_completed_tasks.setObjectName("tab_completed_tasks")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_completed_tasks)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_completed_tasks)
        self.groupBox_3.setMaximumSize(QtCore.QSize(191, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lw_finished_tasks = QtWidgets.QListWidget(self.groupBox_3)
        self.lw_finished_tasks.setMaximumSize(QtCore.QSize(171, 16777215))
        self.lw_finished_tasks.setObjectName("lw_finished_tasks")
        self.verticalLayout_5.addWidget(self.lw_finished_tasks)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_completed_tasks)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tw_finished_task_details = QtWidgets.QTableWidget(self.groupBox_5)
        self.tw_finished_task_details.setObjectName("tw_finished_task_details")
        self.tw_finished_task_details.setColumnCount(0)
        self.tw_finished_task_details.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tw_finished_task_details)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_completed_tasks, "")
        self.tab_history = QtWidgets.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.tabWidget.addTab(self.tab_history, "")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.tabWidget.addTab(self.tab_search, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.lw_finished_tasks.itemClicked['QListWidgetItem*'].connect(MainWindow.onLWFinishedTasksItemClicked)
        self.pb_Ok.clicked.connect(MainWindow.onNewTask)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lw_processing_tasks, self.tw_processing_task_details)
        MainWindow.setTabOrder(self.tw_processing_task_details, self.lw_finished_tasks)
        MainWindow.setTabOrder(self.lw_finished_tasks, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tw_finished_task_details)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "站点："))
        self.lb_current_site.setText(_translate("MainWindow", "ali"))
        self.lb_task_name.setText(_translate("MainWindow", "任务名称:"))
        self.lb_search_conditions.setText(_translate("MainWindow", "搜索关键字："))
        self.pb_Ok.setText(_translate("MainWindow", "确定"))
        self.pb_Cancel.setText(_translate("MainWindow", "清空"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_new_task), _translate("MainWindow", "New Task"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Tasks"))
        item = self.lw_processing_tasks.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "任务"))
        item = self.lw_processing_tasks.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "进度"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Task Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_running_tasks), _translate("MainWindow", "Running Tasks"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tasks"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Task Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_completed_tasks), _translate("MainWindow", "Completed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_history), _translate("MainWindow", "History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("MainWindow", "Search"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "open"))

from taskrunningtable import TaskRunningTable
